In [5]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression

x, y = make_regression(n_samples=100, n_features=3, noise=10)

print("First 5 values of x (Features):\n", x[:5])
print("\nFirst 5 values of y (Targets):\n", y[:5])

# Create an instance of the Linear Regression class
model_linReg = LinearRegression()

# Train the model on our data set using the fit() method
model_linReg.fit(x, y)

# Make predictions using the trained model
predictions = model_linReg.predict(x)

accuracy = model_linReg.score(x, y)
print(f"\nModel Accuracy Score: {accuracy:.4f}")

First 5 values of x (Features):
 [[ 1.01191258  1.13749024 -0.48527792]
 [-0.23053942  1.19021439 -0.36410945]
 [-1.07427303  0.2272144  -0.58994216]
 [-1.02422445  0.25223239 -0.28362131]
 [-1.01922182 -1.22119351  0.9975772 ]]

First 5 values of y (Targets):
 [ 27.18415678  37.63600212 -48.52440697 -41.65622757  16.69732809]

Model Accuracy Score: 0.9920
